### ISSUE TITLE
Realizar diagrama caso de uso para el programa de los peregrinos

### ISSUE THREAD

**Issue by yolandaayuso** [yolandaayuso/ISO22-ISO2-B05#2]

**Comment by gvraul8** [comment]
Los peregrinos utilizan los siguientes casos de uso: 
- Login
- Acceder a la información de las rutas
- Comunicación con otros usuarios
- Proponer punto de interés

**Comment by gvraul8** [comment]
Realizado caso de uso y actualizada wiki.
